import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import ScrollToBottom from "react-scroll-to-bottom";
import { MdAddPhotoAlternate } from "react-icons/md";
import { AiFillHome } from "react-icons/ai";
import { FaEllipsisV, FaDownload, FaSearch } from "react-icons/fa";
import { FiLogOut } from "react-icons/fi";
import {
  MdKeyboardVoice,
  MdSettingsVoice,
  MdMessage,
  MdGroup,
} from "react-icons/md";
import { BsEmojiLaughing, BsFillEmojiLaughingFill } from "react-icons/bs";
// import Layout from "../components/Layout";
// import styles from "../styles/Home.module.scss";

const nameUser = "Alexa Smith";

const dataMessage = [
  {
    id: 1,
    to: "Alexa Smith",
    from: "Zack Martin",
    date: "Mon, 12 Apr 2021 17:00:59 GMT",
    message: "Hello",
  },
  {
    id: 2,
    to: "Alexa Smith",
    from: "Zack Martin",
    date: "Mon, 12 Apr 2021 17:00:59 GMT",
    message: "How are you?",
  },
  {
    id: 3,
    to: "Alexa Smith",
    from: "Zack Martin",
    date: "Mon, 12 Apr 2021 17:00:59 GMT",
    message: "Good, thanks. Nice",
  },
  {
    id: 4,
    to: "Alexa Smith",
    from: "Zack Martin",
    date: "Mon, 12 Apr 2021 17:00:59 GMT",
    message: "How you use whatsapp?",
  },
  ,
  {
    id: 5,
    to: "Zack Martin",
    from: "Alexa Smith",
    date: "Mon, 12 Apr 2021 17:00:59 GMT",
    message: "Yes, thanks",
  },
  {
    id: 6,
    to: "Alexa Smith",
    from: "Zack Martin",
    date: "Mon, 12 Apr 2021 17:00:59 GMT",
    message: "Hello",
  },
  {
    id: 7,
    to: "Alexa Smith",
    from: "Zack Martin",
    date: "Mon, 12 Apr 2021 17:00:59 GMT",
    message: "How are you?",
  },
  {
    id: 8,
    to: "Alexa Smith",
    from: "Zack Martin",
    date: "Mon, 12 Apr 2021 17:00:59 GMT",
    message: "Good, thanks. Nice",
  },
  {
    id: 9,
    to: "Alexa Smith",
    from: "Zack Martin",
    date: "Mon, 12 Apr 2021 17:00:59 GMT",
    message: "How you use whatsapp?",
  },
  ,
  {
    id: 10,
    to: "Zack Martin",
    from: "Alexa Smith",
    date: "Mon, 12 Apr 2021 17:00:59 GMT",
    message: "Yes, thanks",
  },
  {
    id: 11,
    to: "Alexa Smith",
    from: "Zack Martin",
    date: "Mon, 12 Apr 2021 17:00:59 GMT",
    message: "Hello",
  },
  {
    id: 12,
    to: "Alexa Smith",
    from: "Zack Martin",
    date: "Mon, 12 Apr 2021 17:00:59 GMT",
    message: "How are you?",
  },
  {
    id: 13,
    to: "Alexa Smith",
    from: "Zack Martin",
    date: "Mon, 12 Apr 2021 17:00:59 GMT",
    message: "Good, thanks. Nice",
  },
  {
    id: 14,
    to: "Alexa Smith",
    from: "Zack Martin",
    date: "Mon, 12 Apr 2021 17:00:59 GMT",
    message: "How you use whatsapp?",
  },
  ,
  {
    id: 15,
    to: "Zack Martin",
    from: "Alexa Smith",
    date: "Mon, 12 Apr 2021 17:00:59 GMT",
    message: "Yes, thanks",
  },
];

export default function Home() {
  const [currentMessage, setCurrentMessage] = useState("");
  const [tabsMessage, setTabsMessage] = useState(1);

  useEffect(() => {
    const divme = document.querySelector(".card-message-content");
    divme.scrollTop = divme.scrollHeight;
  });

  const toggleTabs = (index) => {
    setTabsMessage(index);
  };

  const onSendClick = () => {
    if (currentMessage.trim() !== "") {
      console.log(currentMessage);
      dataMessage.push({
        id: dataMessage.length + 1,
        to: "Alexa Smith",
        message: currentMessage,
      });
      setCurrentMessage("");
    } else {
      alert("ingrese texto");
    }
  };

  return (
    <>
      <Head>
        <title>Clone WhatsApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/whatsapp-logo.png" />
      </Head>
      <main className="section-whatsapp">
        <section className="container-content">
          <div className="card-view">
            <div className="card-view-user">
              <div className="view-info-user">
                <div className="user-avatar">
                  <Image
                    src="/user3.jpg"
                    alt="User imagen"
                    width={250}
                    height={250}
                    className="user-img"
                  />
                </div>
                <span>Alexa Smith</span>
              </div>
              <div className="head-icon-action">
                <FaDownload size={23} color={"gray"} />
                <FiLogOut size={23} color={"gray"} />
                {/* <img
                  src="https://img.icons8.com/external-kmg-design-glyph-kmg-design/32/000000/external-download-arrow-kmg-design-glyph-kmg-design.png"
                  alt=""
                  className="icon-action"
                />
                <img
                  src="https://img.icons8.com/external-sbts2018-solid-sbts2018/58/000000/external-logout-social-media-sbts2018-solid-sbts2018.png"
                  alt=""
                  className="icon-action"
                /> */}
              </div>
            </div>
            <div className="card-view-search">
              <div className="input-search">
                <input
                  // value={currentMessage}
                  type="text"
                  placeholder="Type a contact"
                  // onChange={(event) => {
                  //   setCurrentMessage(event.target.value);
                  // }}
                  // onKeyPress={(event) => {
                  //   event.key === "Enter" && onSendClick();
                  // }}
                />
                <FaSearch size={25} color={"gray"} className="icon-search" />
              </div>
            </div>
            <div className="card-view-chats">
              <div className="card-tabs-content">
                <div className="items-tabs">
                  <button
                    className={tabsMessage === 1 ? "tabs active-tabs" : "tabs"}
                    onClick={() => toggleTabs(1)}
                  >
                    <AiFillHome
                      size={25}
                      color={"gray"}
                      className="icon-search"
                    />
                  </button>
                  <button
                    className={tabsMessage === 2 ? "tabs active-tabs" : "tabs"}
                    onClick={() => toggleTabs(2)}
                  >
                    <MdMessage
                      size={25}
                      color={"gray"}
                      className="icon-search"
                    />
                  </button>
                  <button
                    className={tabsMessage === 3 ? "tabs active-tabs" : "tabs"}
                    onClick={() => toggleTabs(3)}
                  >
                    <MdGroup size={25} color={"gray"} className="icon-search" />
                  </button>
                </div>
                <div className="content-tabs">
                  <div
                    className={
                      tabsMessage === 1 ? "content active-content" : "content"
                    }
                  >
                    CONTENT ALL
                  </div>
                  <div
                    className={
                      tabsMessage === 2 ? "content active-content" : "content"
                    }
                  >
                    CONTENT MESSAGE
                  </div>
                  <div
                    className={
                      tabsMessage === 3 ? "content active-content" : "content"
                    }
                  >
                    CONTENT GROUP
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="card-messages">
            <div className="card-message-head">
              <div className="head-info-user">
                <div className="user-avatar">
                  <Image
                    src="/user3.jpg"
                    alt="User imagen"
                    width={250}
                    height={250}
                    className="user-img"
                  />
                </div>
                <div className="info-user-name-conection">
                  <span>Zack Martin</span>
                  <span>Seen at Mon, 12 Apr 2021 17:00:59 GMT</span>
                </div>
              </div>
              <div className="head-icon-action">
                {/* <img
                  src="https://img.icons8.com/ios-filled/50/000000/picture.png"
                  alt=""
                  className="icon-action"
                /> */}
                <MdAddPhotoAlternate size={25} color={"gray"} />
                <FaEllipsisV size={25} color={"gray"} />
                {/* <img
                  src="https://img.icons8.com/external-tal-revivo-bold-tal-revivo/24/000000/external-vertical-ellipsis-menu-with-three-dots-expansion-basic-bold-tal-revivo.png"
                  alt=""
                  className="icon-action"
                /> */}
              </div>
            </div>
            <div className="card-message-content">
              {dataMessage.map((item) => {
                return (
                  <div
                    key={item.id}
                    className="message"
                    id={item.to === nameUser ? "message-your" : "message-other"}
                  >
                    {/* <div className="message-avatar"></div> */}
                    <div key={item.id} className="message-content">
                      <div>{item.message}</div>
                      <div>{item.to}</div>
                      <div className="message-date">{`${item.date}`}</div>
                    </div>
                  </div>
                );
              })}
            </div>
            <div className="card-message-send">
              <div className="input-send-message">
                <input
                  value={currentMessage}
                  type="text"
                  placeholder="Type a message"
                  // className="input-send-message"
                  onChange={(event) => {
                    setCurrentMessage(event.target.value.trim());
                  }}
                  onKeyPress={(event) => {
                    event.key === "Enter" && onSendClick();
                  }}
                />
                <BsEmojiLaughing
                  size={25}
                  color={"gray"}
                  className="icon-send-emoji"
                />
              </div>

              <MdKeyboardVoice
                size={40}
                color={"white"}
                className="icon-voice"
              />
              {/* <img
                src="https://img.icons8.com/external-icongeek26-outline-icongeek26/64/000000/external-record-music-icongeek26-outline-icongeek26.png"
                alt=""
                className="icon-action icon-send"
              /> */}
            </div>
          </div>
        </section>
      </main>
      {/* <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Clone WhatsApp</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{" "}
    //       <code className={styles.code}>pages/index.js</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{" "}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  );
}
